version: '3.6'

services:

  ###################################################################

  nginx:
    build:
        context: ./services/nginx
        dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    #depends_on:
    #  - php
    volumes:
      # Configs
      - ./services/nginx/hosts:/etc/nginx/conf.d # Virtual Hosts
      - ./services/nginx/configs:/etc/nginx/configs # Configs 
      - ./logs/nginx:/var/log/nginx # Logs

      # Data
      - ./services/nginx/data:/var/data:rw # Data files
      - /var/www:/var/www  # Work Folder

      # Letsencrypt
      - ./services/nginx/letsencrypt:/etc/letsencrypt # Certs
      - ./logs/letsencrypt:/var/log/letsencrypt # Logs
      - /var/www/html/.well-known/acme-challenge:/var/www/html/.well-known/acme-challenge:rw # ACME

      # TimeZone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Astrakhan

  ###################################################################

  php:
    &php-container
    build:
      context: ./services/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - /var/www:/var/www
      - ./logs/php:/var/log/php # Logs
      - ./services/php/supervisor:/etc/supervisor # Supervisor configs

      # TimeZone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '9000:9000'
      - '9001:9001'
    depends_on:
     - mariadb
    environment:
      - TZ=Europe/Astrakhan
  
#   Очереди для Laravel
#   queue:
#     <<: *php-container
#     working_dir: /var/www/project_name
#     ports:
#       - '9002:9000'
#     command: php artisan queue:work

#   Планировщик для Laravel
#   schedule:
#     <<: *php-container
#     working_dir: /var/www/project_name
#     ports:
#       - '9003:9000'
#     command: php artisan schedule:work

  ###################################################################

  mariadb:
    #image: mariadb:10.7
    build:
      context: ./services/mariadb
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - 3306:3306
    volumes:
      - ./services/mariadb/lib:/var/lib/mysql
      - ./services/mariadb/configs:/etc/mysql
      - ./services/mariadb/data:/var/data:rw # Data files
      #- ./logs/mariadb/:/var/log/mysql # Сбивает права

      #TimeZone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Astrakhan
      - MYSQL_ROOT_PASSWORD=*****
      - MYSQL_USER=syntmind
      - MYSQL_PASSWORD=*****
      #- MYSQL_DATABASE=citizix_db

  ###################################################################
  
  nodejs:
    build: 
      context: ./services/nodejs
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - /var/www:/var/www
    ports:
      - '8080:8080'
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'
    environment:
      - TZ=Europe/Astrakhan
    #extra_hosts:
      #- "host:IP"
    tty: true

  ###################################################################
  
#   cron:
#     build:
#       context: ./services/cron
#       dockerfile: Dockerfile
#     volumes:
#       - /var/www:/var/www
#       - ./logs/cron/:/var/log/ # Logs

#       # TimeZone
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     depends_on:
#       - php
#     environment:
#       - TZ=Europe/Astrakhan

  ###################################################################

#   supervisor:
#     build:
#       context: ./services/supervisor
#       dockerfile: Dockerfile
#     volumes:
#       - /var/www:/var/www
#       - ./logs/supervisor:/var/log/supervisor # Logs

#       # TimeZone
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     depends_on:
#       - mariadb
#     environment:
#       - TZ=Europe/Astrakhan
