#version: '3.8'

services:

  ###################################################################

  nginx:
    build:
        context: ./services/nginx
        dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    #depends_on:
    #  - php
    volumes:
      # Configs
      - ./services/nginx/hosts:/etc/nginx/conf.d # Virtual Hosts
      - ./services/nginx/configs:/etc/nginx/configs # Configs 
      - ./logs/nginx:/var/log/nginx # Logs

      # Data
      - ./services/nginx/data:/var/data:rw # Data files
      - /var/www:/var/www  # Work Folder

      # Letsencrypt
      - ./services/nginx/letsencrypt:/etc/letsencrypt # Certs
      - ./logs/letsencrypt:/var/log/letsencrypt # Logs
      - /var/www/html/.well-known/acme-challenge:/var/www/html/.well-known/acme-challenge:rw # ACME

      # TimeZone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Astrakhan
    #network_mode: host

  ###################################################################

  php:
    &php-container
    build:
      context: ./services/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - /var/www:/var/www
      - ./logs/php:/var/log/php # Logs
      - ./services/php/supervisor:/etc/supervisor # Supervisor configs

      # TimeZone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '9000:9000'
      - '9001:9001'
    depends_on:
     - mariadb
    environment:
      - TZ=Europe/Astrakhan
    dns:
      - 8.8.8.8
      - 8.8.4.4
  
#   Очереди для Laravel
#   queue:
#     <<: *php-container
#     working_dir: /var/www/project_name
#     ports:
#       - '9002:9000'
#     restart: 'always'
#     command: php artisan queue:work

#   Планировщик для Laravel
#   schedule:
#     <<: *php-container
#     working_dir: /var/www/project_name
#     ports:
#       - '9003:9000'
#     restart: 'always'
#     command: php artisan schedule:work

#   octane-project_name:
#     <<: *php-container
#     working_dir: /var/www/project_name
#     ports:
#       - '8001:8000'
#     restart: 'always'
#     command: php artisan octane:start --host=0.0.0.0

  ###################################################################

  mariadb:
    #image: mariadb:10.7
    build:
      context: ./services/mariadb
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - 3306:3306
    volumes:
      - ./services/mariadb/lib:/var/lib/mysql
      - ./services/mariadb/configs:/etc/mysql
      - ./services/mariadb/data:/var/data:rw # Data files
      #- ./logs/mariadb/:/var/log/mysql # Сбивает права

      #TimeZone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Astrakhan
      - MYSQL_ROOT_PASSWORD=*****
      - MYSQL_USER=syntmind
      - MYSQL_PASSWORD=*****
      #- MYSQL_DATABASE=citizix_db

  redis:
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass DaNuPo00@redis --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      
#   mongodb:
#     build:
#       context: ./services/mongodb
#       dockerfile: Dockerfile
#     restart: always
#     ports:
#       - 27020:27017
#     volumes:
#       - ./services/mongodb/data:/data/db
#       - ./services/mongodb/config:/data/configdb
#       - ./services/mongodb/logs:/var/log/mongodb

#     #   #TimeZone
#     #   - /etc/timezone:/etc/timezone:ro
#     #   - /etc/localtime:/etc/localtime:ro
#     environment:
#       - TZ=Europe/Astrakhan
#       - MONGO_INITDB_ROOT_USERNAME=user_name
#       - MONGO_INITDB_ROOT_PASSWORD=password

  ###################################################################
  
  nodejs:
    &nodejs-container
    build: 
      context: ./services/nodejs
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - /var/www:/var/www
    ports:
      - '8080:8080'
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'
    environment:
      - TZ=Europe/Astrakhan
    #extra_hosts:
      #- "host:IP"
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    
#   nodejs-prod-project_name:
#     <<: *nodejs-container
#     working_dir: /var/www/project_name
#     ports:
#       - '3001:3000'
#     restart: 'always'
#     command: node app/server/index.mjs

  ###################################################################
#  uptime-kuma:
#    image: louislam/uptime-kuma:1
#    container_name: uptime-kuma
#    restart: unless-stopped
#    ports:
#      - 4000:3001
#    volumes:
#      - ./services/uptime-kuma/data:/app/data
#      #- ./data:/app/data
#    security_opt:
#      - no-new-privileges:true
