#!/bin/bash

echo 'NGINX'
if [ "$1" = "test" ]
then
    echo '#Testing configs ...'
    docker-compose exec nginx nginx -t
fi

if [ "$1" = "reload" ]
then
    echo '#Testing configs ...'
    output=$(docker-compose exec nginx nginx -t 2>&1)
    echo "$output"

    if [[ $output == *"nginx: the configuration file /etc/nginx/nginx.conf syntax is ok"* && $output == *"nginx: configuration file /etc/nginx/nginx.conf test is successful"* ]]; then
        echo "Nginx configuration is valid."
        echo '#Reload NGINX ...'
        docker-compose exec nginx nginx -s reload
    else
        echo "Nginx configuration is invalid."
        echo "$output"
    fi
fi

if [ "$1" = "restart" ]
then
    echo '#Testing configs ...'
    output=$(docker-compose exec nginx nginx -t 2>&1)
    echo "$output"
    if [[ $output == *"nginx: the configuration file /etc/nginx/nginx.conf syntax is ok"* && $output == *"nginx: configuration file /etc/nginx/nginx.conf test is successful"* ]]; then
        echo "Nginx configuration is valid."
        echo '#Restart container NGINX ...'
        docker-compose restart nginx
    else
        echo "Nginx configuration is invalid."
        echo "$output"
    fi
fi
